### ISSUE TITLE
UI Improvements for Multi-Tenancy Support

### ISSUE THREAD

**Issue by gmolto** [grycap/oscar-ui#100]
1. The "Info" panel should show the EGI User Id for the user. 

2. Some properties of a service display "YesNo". This should be clarified for the user. 

3. Also, a minor grammar correction: "Does this service is exposed?" --> "Is this service exposed?"

5. If a user authenticated through EGI Check-In cannot create a bucket on MinIO, the option "CREATE BUCKET" in the side panel, should not be displayed.

**Comment by gmolto** [comment]
@catttam  Please expand the documentation in https://docs.oscar.grycap.net/multitenancy/ to consider the limitation in bullet point 4.

**Comment by SergioLangaritaBenitez** [comment]
The UI has improved. This is the PR where the changes have been applied (https://github.com/grycap/oscar-ui/pull/104).
