### ISSUE TITLE
UI Improvements for Exposed Services

### ISSUE THREAD

**Issue by gmolto** [grycap/oscar-ui#101]
When showing the details of an Exposed Service, the URL to access the Exposed Service should be shown.

This should be shown in the "SERVICE INFO" panel  that can be expanded when displaying the list of services and also in the "OSCAR services" panel in the "Info" section.

**Comment by SergioLangaritaBenitez** [comment]
The UI has improved. This is the PR where the changes have been applied (https://github.com/grycap/oscar-ui/pull/104)
