### ISSUE TITLE
Improve Preview File on Invoke Panel

### ISSUE THREAD

**Issue by gmolto** [grycap/oscar-ui#94]
Currently, when you select a binary file in the "Invoke" panel for an OSCAR service, its binary content is shown in the text panel. This content should be hidden (since it is meaningless for the user and a binary file cannot be modified by the user from this panel)

**Comment by SergioLangaritaBenitez** [comment]
This feature has been implemented in the following url. Now, if the input is an image, it shows the image. If the input is another kind, a message indicates that the input has been successfully uploaded.
https://github.com/grycap/oscar-ui/pull/107
