### ISSUE TITLE
Support JSON Output Type in Invoke Panel

### ISSUE THREAD

**Issue by gmolto** [grycap/oscar-ui#95]
The "Invoke" panel supports several types but not JSON. Since many AI models from AI4EOSC return a JSON file, it would be convenient to support a collapsable tree-view of the JSON contents of the output for enhanced user experience.

**Comment by SergioLangaritaBenitez** [comment]
This feature has been implemented in the next url.
https://github.com/grycap/oscar-ui/pull/107
